### ISSUE TITLE
[FEATURE] Golang generator should include comments from parameter descriptions

### ISSUE THREAD

**Issue by TertiumOrganum1** [asyncapi/modelina#2116]
### Why do we need this improvement?

Golang generator should include comments from parameter descriptions

### How will this change help?

Golang generator should include comments from parameter descriptions

### How could it be implemented/designed?

Golang generator should include comments from parameter descriptions

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

None

**Comment by jonaslagoni** [comment]
Makes sense, happy to accept PRs 🙏

**Comment by toffee-k21** [comment]
Hey @jonaslagoni, I think this change should apply to all the languages we support, not just Golang

**Comment by jonaslagoni** [comment]
Feel free to create an issue per language where this is missing (some already have it), or jump straight into a PR @toffee-k21 ✌️

**Comment by jonaslagoni** [comment]
We got multiple languages that dont have a preset that include descriptions. 

>I can't fix it myself in your code, but it should be very quick for those how know modelina codebase

1. Copy https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/presets/DescriptionPreset.ts to start off with for Go https://github.com/asyncapi/modelina/tree/master/src/generators/go
2. Adapt the preset
3. Add a test

Done.

**Comment by TertiumOrganum1** [comment]
> We got multiple languages that dont have a preset that include descriptions.
> 
> > I can't fix it myself in your code, but it should be very quick for those how know modelina codebase
> 
> This is the basic recipe:
> 
> 1. Copy https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/presets/DescriptionPreset.ts to start off with for Go https://github.com/asyncapi/modelina/tree/master/src/generators/go
> 2. Adapt the preset
> 3. Add a test
> 4. Create a PR

sorry this code doesn't make sense to me at all, I'm from c++/go

**Comment by TertiumOrganum1** [comment]
> We got multiple languages that dont have a preset that include descriptions.
> 
> > I can't fix it myself in your code, but it should be very quick for those how know modelina codebase
> 
> This is the basic recipe:
> 
> 1. Copy https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/presets/DescriptionPreset.ts to start off with for Go https://github.com/asyncapi/modelina/tree/master/src/generators/go
> 2. Adapt the preset
> 3. Add a test
> 4. Create a PR

[CommonPreset.ts.txt](https://github.com/user-attachments/files/17611276/CommonPreset.ts.txt)

Ok,  I've copied and adopted DescriptionPreset.ts from typescript to go, added it to go/presets/index.ts, but it never called and no comments in my generated sources. What should I do to make it work?

nothing new in comments, annoying "ResponsePayload represents a ResponsePayload model" still exists, so I assume that my preset even doesn't called. Maybe it is not plugged in inside modelina for golang?
